version: '3'
services:
    poll:
      build: ./poll
      restart: on-failure
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      ports:
        - "5000:80"
      networks:
        - poll-tier
      depends_on:
        - "redis"

    result:
        build: ./result
        restart: on-failure
        environment:
          - REDIS_HOST=redis
          - POSTGRES_DB=votes
          - POSTGRES_HOST=db
          - POSTGRES_PORT=5432
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=postgres
        networks:
          - result-tier
        ports:
          - "5001:80"
        depends_on:
          - "db"

    worker:
      build: ./worker
      restart: on-failure
      environment:
        - REDIS_HOST=redis
        - POSTGRES_DB=votes
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=postgres
      networks:
        - back-tier
      depends_on:
        - "db"
        - "redis"


    redis:
      image: redis:7
      restart: on-failure
      ports:
        - "6379"
      networks:
        - poll-tier
        - back-tier


    db:
      image: postgres:16
      restart: on-failure
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
      volumes:
        - ./schema.sql:/docker-entrypoint-init-db.d/schema.sql
        - db-data:/var/lib:postgresql/data
      networks:
        - result-tier
        - back-tier


volumes:
  db-data:

networks:
  poll-tier:
    driver: bridge
  result-tier:
    driver: bridge
  back-tier:
    driver: bridge
